# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 304)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.slider_red = QtWidgets.QSlider(self.centralwidget)
        self.slider_red.setGeometry(QtCore.QRect(410, 80, 160, 16))
        self.slider_red.setOrientation(QtCore.Qt.Horizontal)
        self.slider_red.setObjectName("slider_red")
        self.slider_green = QtWidgets.QSlider(self.centralwidget)
        self.slider_green.setGeometry(QtCore.QRect(410, 120, 160, 16))
        self.slider_green.setOrientation(QtCore.Qt.Horizontal)
        self.slider_green.setObjectName("slider_green")
        self.slider_blue = QtWidgets.QSlider(self.centralwidget)
        self.slider_blue.setGeometry(QtCore.QRect(410, 160, 160, 16))
        self.slider_blue.setOrientation(QtCore.Qt.Horizontal)
        self.slider_blue.setObjectName("slider_blue")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 256, 256))
        self.label.setObjectName("label")
        self.slider_threshold = QtWidgets.QSlider(self.centralwidget)
        self.slider_threshold.setGeometry(QtCore.QRect(410, 200, 160, 16))
        self.slider_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold.setObjectName("slider_threshold")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 80, 60, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 120, 60, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 160, 60, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 200, 81, 17))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "IMAGE"))
        self.label_2.setText(_translate("MainWindow", "RED"))
        self.label_3.setText(_translate("MainWindow", "GREEN"))
        self.label_4.setText(_translate("MainWindow", "BLUE"))
        self.label_5.setText(_translate("MainWindow", "THRESHOLD"))
